version: '3'

services:

  spa:
    image: node:lts-alpine
    restart: "no"
    environment:
      - API_URL=${API_URL}
    volumes:
      - ./app:/app
    ports:
      - ${NGINX_PORT}:8080
    working_dir: /app
    command: [sh, -c, "npm install && npm run serve"]
    #command: tail -f /dev/null
